<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 10:48:51.
 */
class BlackTypeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BlackType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BlackType;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pgn\tags\BlackType::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        $expected = 'BlackType';
        $result = $this->object->getName();
        
        $this->assertEquals($expected, $result);
    }

}
