<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 11:18:53.
 */
class BlackTitleTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BlackTitle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BlackTitle;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () === 'BlackTitle'.
     *
     * @covers pgn\tags\BlackTitle::getName
     */
    public function testGetName() {
        $this->assertSame(
                'BlackTitle'
                , $this->object->getName()
        );
    }

}
