<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 07:02:23.
 */
class ECOTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ECO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ECO;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("A00") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate() {
        $this->assertSame(
                true
                , $this->object->validate("A00")
        );
    }

    /**
     * Generated from @assert ("A00/00") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate2() {
        $this->assertSame(
                true
                , $this->object->validate("A00/00")
        );
    }

    /**
     * Generated from @assert ("E99") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate3() {
        $this->assertSame(
                true
                , $this->object->validate("E99")
        );
    }

    /**
     * Generated from @assert ("E99/99") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate4() {
        $this->assertSame(
                true
                , $this->object->validate("E99/99")
        );
    }

    /**
     * Generated from @assert ("C12/34") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate5() {
        $this->assertSame(
                true
                , $this->object->validate("C12/34")
        );
    }

    /**
     * Generated from @assert ("C21") === true.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate6() {
        $this->assertSame(
                true
                , $this->object->validate("C21")
        );
    }

    /**
     * Generated from @assert (NULL) === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate7() {
        $this->assertSame(
                false
                , $this->object->validate(NULL)
        );
    }

    /**
     * Generated from @assert ("A") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate8() {
        $this->assertSame(
                false
                , $this->object->validate("A")
        );
    }

    /**
     * Generated from @assert ("A0") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate9() {
        $this->assertSame(
                false
                , $this->object->validate("A0")
        );
    }

    /**
     * Generated from @assert ("A00/0") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate10() {
        $this->assertSame(
                false
                , $this->object->validate("A00/0")
        );
    }

    /**
     * Generated from @assert ("asdf") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate11() {
        $this->assertSame(
                false
                , $this->object->validate("asdf")
        );
    }

    /**
     * Generated from @assert (123) === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate12() {
        $this->assertSame(
                false
                , $this->object->validate(123)
        );
    }

    /**
     * Generated from @assert ("*") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate13() {
        $this->assertSame(
                false
                , $this->object->validate("*")
        );
    }

    /**
     * Generated from @assert ("????.??.??") === false.
     *
     * @covers pgn\tags\ECO::validate
     */
    public function testValidate14() {
        $this->assertSame(
                false
                , $this->object->validate("????.??.??")
        );
    }

    /**
     * @covers pgn\tags\ECO::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pgn\tags\ECO::validPattern
     * @todo   Implement testValidPattern().
     */
    public function testValidPattern() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
