<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 10:43:53.
 */
class EventSponsorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var EventSponsor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EventSponsor;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () === "EventSponsor".
     *
     * @covers pgn\tags\EventSponsor::getName
     */
    public function testGetName() {
        $this->assertSame(
                "EventSponsor"
                , $this->object->getName()
        );
    }

}
