<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 11:44:01.
 */
class TerminationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Termination
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Termination;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () === 'Termination'.
     *
     * @covers pgn\tags\Termination::getName
     */
    public function testGetName() {
        $this->assertSame(
                'Termination'
                , $this->object->getName()
        );
    }

    /**
     * Generated from @assert ("abandoned") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate() {
        $this->assertSame(
                true
                , $this->object->validate("abandoned")
        );
    }

    /**
     * Generated from @assert ("adjudication") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate2() {
        $this->assertSame(
                true
                , $this->object->validate("adjudication")
        );
    }

    /**
     * Generated from @assert ("death") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate3() {
        $this->assertSame(
                true
                , $this->object->validate("death")
        );
    }

    /**
     * Generated from @assert ("emergency") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate4() {
        $this->assertSame(
                true
                , $this->object->validate("emergency")
        );
    }

    /**
     * Generated from @assert ("normal") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate5() {
        $this->assertSame(
                true
                , $this->object->validate("normal")
        );
    }

    /**
     * Generated from @assert ("rules infraction") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate6() {
        $this->assertSame(
                true
                , $this->object->validate("rules infraction")
        );
    }

    /**
     * Generated from @assert ("time forfeit") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate7() {
        $this->assertSame(
                true
                , $this->object->validate("time forfeit")
        );
    }

    /**
     * Generated from @assert ("unterminated") === true.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate8() {
        $this->assertSame(
                true
                , $this->object->validate("unterminated")
        );
    }

    /**
     * Generated from @assert ("human") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate9() {
        $this->assertSame(
                false
                , $this->object->validate("human")
        );
    }

    /**
     * Generated from @assert ("program") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate10() {
        $this->assertSame(
                false
                , $this->object->validate("program")
        );
    }

    /**
     * Generated from @assert ("person") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate11() {
        $this->assertSame(
                false
                , $this->object->validate("person")
        );
    }

    /**
     * Generated from @assert ("software") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate12() {
        $this->assertSame(
                false
                , $this->object->validate("software")
        );
    }

    /**
     * Generated from @assert (3.1) === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate13() {
        $this->assertSame(
                false
                , $this->object->validate(3.1)
        );
    }

    /**
     * Generated from @assert ("4.1.2") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate14() {
        $this->assertSame(
                false
                , $this->object->validate("4.1.2")
        );
    }

    /**
     * Generated from @assert ("-") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate15() {
        $this->assertSame(
                false
                , $this->object->validate("-")
        );
    }

    /**
     * Generated from @assert (NULL) === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate16() {
        $this->assertSame(
                false
                , $this->object->validate(NULL)
        );
    }

    /**
     * Generated from @assert ("A") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate17() {
        $this->assertSame(
                false
                , $this->object->validate("A")
        );
    }

    /**
     * Generated from @assert ("asdf") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate18() {
        $this->assertSame(
                false
                , $this->object->validate("asdf")
        );
    }

    /**
     * Generated from @assert ("*") === false.
     *
     * @covers pgn\tags\Termination::validate
     */
    public function testValidate19() {
        $this->assertSame(
                false
                , $this->object->validate("*")
        );
    }

    /**
     * @covers pgn\tags\Termination::validPattern
     * @todo   Implement testValidPattern().
     */
    public function testValidPattern() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
