<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 09:05:47.
 */
class TimeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Time
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Time;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("00:00:00") === true.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate() {
        $this->assertSame(
                true
                , $this->object->validate("00:00:00")
        );
    }

    /**
     * Generated from @assert ("00.00.00") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate2() {
        $this->assertSame(
                false
                , $this->object->validate("00.00.00")
        );
    }

    /**
     * Generated from @assert ("19:33:15") === true.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate3() {
        $this->assertSame(
                true
                , $this->object->validate("19:33:15")
        );
    }

    /**
     * Generated from @assert ("20:50:09") === true.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate4() {
        $this->assertSame(
                true
                , $this->object->validate("20:50:09")
        );
    }

    /**
     * Generated from @assert ("23:59:59") === true.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate5() {
        $this->assertSame(
                true
                , $this->object->validate("23:59:59")
        );
    }

    /**
     * Generated from @assert ("-1:33:15") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate6() {
        $this->assertSame(
                false
                , $this->object->validate("-1:33:15")
        );
    }

    /**
     * Generated from @assert ("00:-1:15") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate7() {
        $this->assertSame(
                false
                , $this->object->validate("00:-1:15")
        );
    }

    /**
     * Generated from @assert ("00:00:-1") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate8() {
        $this->assertSame(
                false
                , $this->object->validate("00:00:-1")
        );
    }

    /**
     * Generated from @assert ("24:00:00") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate9() {
        $this->assertSame(
                false
                , $this->object->validate("24:00:00")
        );
    }

    /**
     * Generated from @assert ("19:60:00") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate10() {
        $this->assertSame(
                false
                , $this->object->validate("19:60:00")
        );
    }

    /**
     * Generated from @assert ("19:59:60") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate11() {
        $this->assertSame(
                false
                , $this->object->validate("19:59:60")
        );
    }

    /**
     * Generated from @assert (2) === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate12() {
        $this->assertSame(
                false
                , $this->object->validate(2)
        );
    }

    /**
     * Generated from @assert ("a") === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate13() {
        $this->assertSame(
                false
                , $this->object->validate("a")
        );
    }

    /**
     * Generated from @assert (NULL) === false.
     *
     * @covers pgn\tags\Time::validate
     */
    public function testValidate14() {
        $this->assertSame(
                false
                , $this->object->validate(NULL)
        );
    }

    /**
     * @covers pgn\tags\Time::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers pgn\tags\Time::validPattern
     * @todo   Implement testValidPattern().
     */
    public function testValidPattern() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
