<?php
namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-18 at 20:17:46.
 */
class WhiteEloTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WhiteElo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WhiteElo;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert () === "WhiteElo".
     *
     * @covers pgn\tags\WhiteElo::getName
     */
    public function testGetName()
    {
        $this->assertSame(
            "WhiteElo"
,
            $this->object->getName()
        );
    }

    /**
     * Generated from @assert () === "-".
     *
     * @covers pgn\tags\WhiteElo::getDefaultValue
     */
    public function testGetDefaultValue()
    {
        $this->assertSame(
            "-"
,
            $this->object->getDefaultValue()
        );
    }
}
