<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 11:00:55.
 */
class WhiteNATest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WhiteNA
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WhiteNA;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () === 'WhiteNA'.
     *
     * @covers pgn\tags\WhiteNA::getName
     */
    public function testGetName() {
        $this->assertSame(
                'WhiteNA'
                , $this->object->getName()
        );
    }

    /**
     * Generated from @assert ("-") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate() {
        $this->assertSame(
                true
                , $this->object->validate("-")
        );
    }

    /**
     * Generated from @assert ("email@domain.com") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate2() {
        $this->assertSame(
                true
                , $this->object->validate("email@domain.com")
        );
    }

    /**
     * Generated from @assert ("http://www.meusite.com") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate3() {
        $this->assertSame(
                true
                , $this->object->validate("http://www.meusite.com")
        );
    }

    /**
     * Generated from @assert ("http://www.meusite.com/diretorio") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate4() {
        $this->assertSame(
                true
                , $this->object->validate("http://www.meusite.com/diretorio")
        );
    }

    /**
     * Generated from @assert ("http://www.meusite.com/diretorio/pagina.html") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate5() {
        $this->assertSame(
                true
                , $this->object->validate("http://www.meusite.com/diretorio/pagina.html")
        );
    }

    /**
     * Generated from @assert ("https://meusite.com/diretorio/pagina.html") === true.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate6() {
        $this->assertSame(
                true
                , $this->object->validate("https://meusite.com/diretorio/pagina.html")
        );
    }

    /**
     * Generated from @assert ("Tal, Mikhail N.") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate7() {
        $this->assertSame(
                false
                , $this->object->validate("Tal, Mikhail N.")
        );
    }

    /**
     * Generated from @assert ("van der Wiel, Johan") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate8() {
        $this->assertSame(
                false
                , $this->object->validate("van der Wiel, Johan")
        );
    }

    /**
     * Generated from @assert ("Acme Pawngrabber v.3.2") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate9() {
        $this->assertSame(
                false
                , $this->object->validate("Acme Pawngrabber v.3.2")
        );
    }

    /**
     * Generated from @assert ("?") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate10() {
        $this->assertSame(
                false
                , $this->object->validate("?")
        );
    }

    /**
     * Generated from @assert (NULL) === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate11() {
        $this->assertSame(
                false
                , $this->object->validate(NULL)
        );
    }

    /**
     * Generated from @assert ("ab") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate12() {
        $this->assertSame(
                false
                , $this->object->validate("ab")
        );
    }

    /**
     * Generated from @assert (", ") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate13() {
        $this->assertSame(
                false
                , $this->object->validate(", ")
        );
    }

    /**
     * Generated from @assert (",a") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate14() {
        $this->assertSame(
                false
                , $this->object->validate(",a")
        );
    }

    /**
     * Generated from @assert ("a") === false.
     *
     * @covers pgn\tags\WhiteNA::validate
     */
    public function testValidate15() {
        $this->assertSame(
                false
                , $this->object->validate("a")
        );
    }

    /**
     * @covers pgn\tags\WhiteNA::validPattern
     * @todo   Implement testValidPattern().
     */
    public function testValidPattern() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
