<?php

namespace pgn\tags;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 11:09:27.
 */
class WhiteUSFTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WhiteUSCF
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WhiteUSCF;
        echo __CLASS__ . '::' . $this->getName() . "\n";
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert () === "WhiteUSCF".
     *
     * @covers pgn\tags\WhiteUSCF::getName
     */
    public function testGetName() {
        $this->assertSame(
                "WhiteUSCF"
                , $this->object->getName()
        );
    }

}
